openapi: 3.0.0
info:
  title: Volunteer Availability API
  description: API for managing volunteer and campus availability
  version: 1.0.0
servers:
  - url: http://localhost:4567
    description: Development server

paths:
  /volunteers:
    put:
      summary: Update a volunteer's availability
      description: Update or add to a volunteer's available time slots
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - i
              properties:
                id:
                  type: string
                  description: Volunteer's ID
                i:
                  type: number
                  description: Index of availability to update
                from:
                  type: string
                  format: date-time
                  description: Start time of availability
                to:
                  type: string
                  format: date-time
                  description: End time of availability
      responses:
        '200':
          description: Availability updated successfully
        '400':
          description: Invalid input data
        '204':
          description: No volunteer found with the given ID

  /volunteers/{id}:
    get:
      summary: Get a volunteer's availability
      description: Retrieve a volunteer's available time slots
      parameters:
        - in: path
          name: id
          required: true
          description: Volunteer's ID
          schema:
            type: string
      responses:
        '200':
          description: A list of available time slots
        '400':
          description: Invalid ID
        '204':
          description: No volunteer found with the given ID

  /campuses:
    get:
      summary: Get all campuses' availability
      description: Retrieve available time slots for all campuses
      responses:
        '200':
          description: A list of available time slots for all campuses
        '204':
          description: No campuses found

components:
  schemas:
    Volunteer:
      type: object
      required:
        - firstName
        - lastName
        - email
        - phone
      properties:
        _id:
          type: string
          description: MongoDB generated ID
        firstName:
          type: string
          description: Volunteer's first name
        lastName:
          type: string
          description: Volunteer's last name
        availability:
          type: array
          items:
            type: object
            properties:
              from:
                type: string
                format: date-time
                description: Start time of availability
              to:
                type: string
                format: date-time
                description: End time of availability
        email:
          type: string
          description: Volunteer's email address
        phone:
          type: string
          description: Volunteer's phone number
    
    Campus:
      type: object
      required:
        - name
        - address
      properties:
        _id:
          type: string
          description: MongoDB generated ID
        name:
          type: string
          description: Campus name
        address:
          type: string
          description: Campus physical address
        availability:
          type: array
          items:
            type: object
            properties:
              from:
                type: string
                format: date-time
                description: Start time of availability
              to:
                type: string
                format: date-time
                description: End time of availability